### ISSUE TITLE
"Skipping the ReSharper issue at line ..." for included Files

### ISSUE THREAD

**Issue by baumerik** [GregBartlett/sonar-resharper#21]
on our Build we have the Logmessages for each file:
`2016-07-05T11:06:08.4924234Z 11:06:08.336 INFO  - Skipping the ReSharper issue at line 177 whose file "D:\T1\6\Product\Source\Solution\..\Platform\Web\AccessControl\CheckAccessModule.cs" is not in SonarQube.`
But the sources are uploaded to SonarServer.

out Structure is as the Following:
- Solutions
  - Solution.sln <-- used for Build, Analysis, ...
  - ...
- Platform
  - Projects\
  - ...
- App
  - Projects
  - ...
- Tests
  - Projects
  - ...

is there a Probleme with the relative Path?
see: http://stackoverflow.com/questions/27091855/sonarresharper-with-projects-containing-linked-files

**Comment by baumerik** [comment]
Moving the Solution on Root does not solve the issue. 
`2016-07-07T09:48:56.9831799Z INFO: Skipping the ReSharper issue at line 182 whose file "D:\A1\17\Product\Source\Platform\Web\AccessControl\CheckAccessModule.cs" is not in SonarQube.`

Are there some other settings I can check?

**Comment by afterbangx** [comment]
I have this same issue and would really like to know a solution. The project I'm currently having this issue in takes almost 3 hours to run because of these "skipped" files. The files are in SonarQube though as you can see here: 

![image](https://cloud.githubusercontent.com/assets/12399066/17182202/5c4d60d6-53e8-11e6-9456-9dd6ad6d557c.png)

![image](https://cloud.githubusercontent.com/assets/12399066/17182397/f6cc9230-53e8-11e6-855c-11741f1b52fc.png)

**Comment by giacgbj** [comment]
Same problem here and increased jobs' duration and logs.

**Comment by GregBartlett** [comment]
If you are using a newer version of SonarQube, I would NOT use this plugin until it’s been brought up to date.  I’m still trying to find time to get it up to using the plugin api for 5.6 but there are A LOT of deprecated methods since 4.5 and sonarqube has changed a lot since then in regards to analysis and rules.

 

Take a look at the Pull request, if you think that will resolve the issue, I’ll bring it in.

**Comment by giacgbj** [comment]
I'd remove this plugin, but I think many rules have not already been migrated to the SonarQube's one.

According to the comments regarding the pull request it seems that it could work.

You can try to merge the pull the request so we can test the new release.

**Comment by GregBartlett** [comment]
@giacgbj If you hadn't removed this yet, I got the fix that @rikvandenberg had provided a long time ago into a release that can be pulled from the releases tab.  Sorry for taking so long to get this going.
