### ISSUE TITLE
Resharper plugin related error in General Settings

### ISSUE THREAD

**Issue by mmajcica** [GregBartlett/sonar-resharper#23]
Since I upgraded Sonar to version 6.1 I do see in general settings the following message:

> 'sonar.resharper.installDirectory' and 'sonar.resharper.inspectCodePath' cannot be used at the same time as they refer to the same setting

![image](https://cloud.githubusercontent.com/assets/3026551/19687994/028199b0-9ac8-11e6-80fc-d0256388f50d.png)

Does anyone know why of it and how to fix it?

**Comment by GregBartlett** [comment]
I wouldn’t use this plugin at this time.. it is SO FAR out of date and hasn’t been brought up from the 4.5 plugin and soooo much has changed.

I’m half tempted to just rewrite it using the 5.6 plugin api and take what I can from the original.  Just a lot of deprecated code :(

**Comment by mberubenet** [comment]
Any plan to fix that plugins soon ? Losing the Resharper integration is a big problem. I don't know much how SonarQube works but this error message prevent the settings to display properly. It there a workaround ? Thanks

**Comment by GregBartlett** [comment]
I corporates the change into he branch but having issues with appveyor building it :( 
As soon as I resolve that issue and get a good build I'll update the version and get it out there 


Sent via the Samsung Galaxy Note® 4, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by GregBartlett** [comment]
Oh wait this was the 6.1 thread.  No I haven't gotten this thing going for that.
I don't have an eta, sonar documentation for plug in development isn't very good and am still trying to understand it


Sent via the Samsung Galaxy Note® 4, an AT&T 4G LTE smartphone

-------- Original message --------

**Comment by mberubenet** [comment]
Well, for what I see, version 2.0 of the plugins works pretty well on SonarQube 6.2 except for the error message specified at the beginning of the post the prevent the setting page to display ANY values. My guest (but I'm not an expert in SonarQube in anyway) is that if you comment line 102 or 115 of [ReSharperPlugins.java](sonar-resharper/src/main/java/org/sonar/plugins/resharper/ReSharperPlugin.java), the settings page of SonarQube should stop complaining about 2 keys for the same property. I wish I could submit a pull request myself but I haven't done java since college (I'm a C# dev you can guess) and even if I can propably write the code, I unfortunately don't know much about the modern java tool chain (maven, appveyor, jUnit etc,). It's not the thing the teach you at school !

Doing that, I'm pretty sure the plugins will work well enough to continue to be used until an update to the 6+ API is done. If you think it could break older versions of SonarQube, maybe start an hotfix branch for that. 

If you found proper documentation about that and maybe you could gave me some tips on how to setup a working java development environment, I would be glad to help you on that. We rely a lot on ReSharper and that integration is a must for us.

Thanks

**Comment by GregBartlett** [comment]
Thank you.  Let me get the build working on appveyor and take a look at whether your suggestions will break anything for prior versions. I’m by no means a java developer.  I’m a C# .Net Developer as well, who tinkers ;)

**Comment by GregBartlett** [comment]
@mberubenet .. I removed the install path variable as it wasnt being used anywhere. Look for release > 2.16 in a little bit while i pull and build and release

**Comment by GregBartlett** [comment]
@mmajcica @mberubenet v2.17 released, give it a shot in a test environment first if you have one

**Comment by mberubenet** [comment]
I will. Thanks a lot for your effort, I'll tell you how it goes.

**Comment by GregBartlett** [comment]
👍

**Comment by mberubenet** [comment]
Just tested it. Looks good. Analysis still work as expected and no more error it the administration and project setting page. Thanks again !

**Comment by GregBartlett** [comment]
awesome, I'll close out this issue.  Is the other issue where it's doing the duplicate lines thing gone too?

**Comment by GregBartlett** [comment]
this one: https://github.com/GregBartlett/sonar-resharper/issues/21

**Comment by GregBartlett** [comment]
Yeah I think originally the default was INFO and it was changed to only show if you tell it to be more verbose.  When I have time I'll look at the code more closely to figure out why it happens in general, but thanks for taking a look.
